title: Christina Cao
description: Product Designer
author: Christina Cao
# theme: jekyll-theme-minimal
email: chomoon@qq.com
copyright: Copyright Â© 2021-2021
<<<<<<< HEAD
favicon: "favicon.ico"
=======
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
favicon: "favicon.ico"
>>>>>>> parent of a56dba1... 34
